# Jekyll Web Awesome Plugin Example Site
title: "Jekyll Web Awesome Plugin Examples"
description: "A showcase of all Web Awesome components supported by the jekyll-webawesome plugin"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Add the plugin to your plugins list
plugins:
  - jekyll-webawesome

# Enable debug output (optional)
webawesome:
  debug: true

  # Control which file types to transform (default: both true)
  transform_pages: true      # Transform pages (like index.md, about.md)
  transform_documents: true  # Transform documents (like blog posts in _posts)
  
  # Image dialog configuration
  # Can be a simple boolean: true/false
  # Or a hash with options:
  image_dialog:
    enabled: true
    default_width: 90vh      # Default width for image dialogs (e.g., 90vh, 80%, 1200px)

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
