# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.0'
gem 'markawesome', path: '../../markawesome'
gem 'logger'

group :jekyll_plugins do
  gem 'jekyll-webawesome', path: '../'
end
